export const colors = {
  background: "#f5f3ff",
  cardBackground: "#ffffff",
  textPrimary: "#1a202c",
  textSecondary: "#64748b",
  textMuted: "#94a3b8",
  heroBg: "#1e1b4b",
  heroGradientEnd: "#2d1b69",
  purplePrimary: "#8b5cf6",
  purpleDark: "#6366f1",
  purpleLight: "#e9d5ff",
  purpleSoft: "#f0f4ff",
  successBg: "#dcfce7",
  successText: "#166534",
  successBorder: "#16a34a",
  warningBg: "#fef3c7",
  warningText: "#92400e",
  dangerBg: "#fee2e2",
  dangerText: "#991b1b",
  dangerNumber: "#dc2626",
  badgeAutoBg: "#dcfce7",
  badgeAutoText: "#166534",
  badgeManualBg: "#f3f4f6",
  badgeManualText: "#374151",
  badgeTriggerBg: "#dbeafe",
  badgeTriggerText: "#1e40af",
  borderLight: "#e2e8f0",
  buttonReject: "#f43f5e",
  buttonSecondaryBg: "#f1f5fe",
  buttonSecondaryText: "#4f46e5",
};

export const shadows = {
  card: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  hero: {
    shadowColor: "#2d1b69",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 6,
  },
  button: {
    shadowColor: "#6366f1",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
};
